#!/usr/bin/env bash

RED='\e[31m'
GREEN='\e[32m'
DEFAULT='\e[39m'
HIDE_CURSOR='\e[?25l'
SHOW_CURSOR='\e[?25h'
errored=false
spinner_pid=

ESSENTIAL_PACKAGES=(
	btop
	fastfetch
	fzf
	gcc
	git
	gnuplot
	jq
	juliaup
	make
	ncdu
	neovim
	python3-numpy
	ShellCheck
	stow
	trash-cli
	typst
	zathura
	zathura-plugin-cb
	zathura-plugin-pdf-mupdf
)

DESKTOP_PACKAGES=(
	cava
	flameshot
	flatpak
	foot
	FreeCAD
	gimp
	ibm-plex-mono-fonts
	ibm-plex-sans-fonts
	inkscape
	iosevka-fonts
	keyd
	kicad
	kid3
	kronometer
	libnotify-tools
	mpd
	mpDris2
	mpv
	opi
	qbittorrent
	qview
	rmpc
	shntool
	syncthing
)

WSL_PACKAGES=(
	bash-completion
	gzip
	man-pages
	tar
)

TEXLIVE_PACKAGES=(
	adjustbox
	beamer
	biber
	biblatex
	biblatex-ieee
	booktabs
	caption
	cleveref
	csquotes
	datatool-english
	datatool-regions
	eso-pic
	float
	fontaxes
	glossaries-english
	glossaries-extra
	graphbox
	ieeetran
	koma-script
	latexmk
	listings
	matlab-prettifier
	mhchem
	newtx
	ninecolors
	plex
	pgfplots
	siunitx
	soul
	tabularray
	uantwerpendocs
	unicode-math
	xcolor
	xstring
)

FLATPAKS=(
	com.discordapp.Discord
	com.github.ahrm.sioyek
	org.jabref.jabref
	org.localsend.localsend_app
)

spinner() {
	local i=1
	local prompt="$1"
	local spinchars='\|/-'

	echo -n "$prompt [" >&3
	while : ; do
		echo -en "${spinchars:i++%4:1}]" >&3
		echo -en '\b\b' >&3
		sleep 0.1
	done
}

start-spinner() {
	spinner "$1" &
	spinner_pid=$!
}

stop-spinner() {
    if [[ -n $spinner_pid ]]; then
        kill "$spinner_pid"
        unset spinner_pid
		if [[ $errored == false ]]; then
			echo -e "${GREEN}✔${DEFAULT}" >&3
		else
			echo -e "${RED}x${DEFAULT}" >&3
			echo -e "$message" >&3
		fi
		errored=false
		message=""
	fi
}

error-message() {
	[[ $? == 0 ]] && return
	[[ -n $message ]] && message+='\n'
    message+="\tERROR: $1"
}

cleanup() {
	stop-spinner
	# Restore sudo timeout to default
	sudo rm -f /etc/sudoers.d/timeout
	# Remove temporary polkit Flatpak rule
	sudo rm -f /etc/polkit-1/rules.d/45-flatpak-nopw.rules
	echo -en "$SHOW_CURSOR" >&3
}

is-wsl () {
	[[ -d /mnt/c/Windows ]]
}

sudo-timeout() {
	# Temporarily increase timeout for sudo command to prevent being password prompted multiple times
	echo 'Defaults timestamp_timeout=30' | sudo tee /etc/sudoers.d/timeout
}

flatpak-no-pw() {
	# Temporarily add a rule that turns of the need for a password to install Flatpaks system-wide
	sudo tee /etc/polkit-1/rules.d/45-flatpak-nopw.rules > /dev/null <<-EOF
		polkit.addRule(function(action, subject) {
			if (action.id.startsWith("org.freedesktop.Flatpak") &&
				subject.user == "$USER") {
					return polkit.Result.YES;
				}
		});
	EOF
}

set-hostname() {
	sudo hostnamectl hostname "$host_name"
}

configure-wsl() {
	if ! grep -q appendWindowsPath /etc/wsl.conf; then
		echo -e '[interop]\nappendWindowsPath = false' | sudo tee -a /etc/wsl.conf
	fi
}

configure-zypper() {
	sudo sed -e 's/^# download.max_concurrent_connections = 5/download.max_concurrent_connections = 10/' \
		-e 's/^# download.min_download_speed = 0/download.min_download_speed = 20000/' \
		-i /etc/zypp/zypp.conf
}

open-ports() {
	# These ports need to be open for LocalSend to work
	sudo firewall-cmd --permanent --add-port=53317/tcp
	sudo firewall-cmd --permanent --add-port=53317/udp
	sudo firewall-cmd --reload
}

update-system() {
	sudo zypper --non-interactive dist-upgrade --allow-vendor-change
}

install-wsl-packages() {
	sudo zypper --non-interactive remove --clean-deps busybox-gzip busybox-which
	sudo zypper --non-interactive install "${WSL_PACKAGES[@]}"
}

install-essential-packages() {
	sudo zypper --non-interactive install "${ESSENTIAL_PACKAGES[@]}"
}

install-desktop-packages() {
	# Lock prevents Iosevka variants from being installed on updates
	sudo zypper --non-interactive addlock iosevka-*-fonts
	sudo zypper --non-interactive install "${DESKTOP_PACKAGES[@]}"
}

install-codecs() {
	opi -n codecs
}

install-flatpaks() {
	flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
	flatpak install --assumeyes --noninteractive flathub "${FLATPAKS[@]}"
}

install-texlive() {
	curl -LOO https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz.sha512

	if sha512sum -c --ignore-missing install-tl-unx.tar.gz.sha512; then
		tar -xf install-tl-unx.tar.gz

		local texlive_release=$(grep 'ReleaseYear = *' "$HOME"/install-tl-*/tlpkg/TeXLive/TLConfig.pm | grep -o '[0-9]\{4\}')

		[[ -d $HOME/.opt/texlive/$texlive_release ]] && rm -rf "$HOME"/install-tl* && return 0

		tee > profile <<-EOF
			selected_scheme scheme-custom
			TEXDIR $HOME/.opt/texlive/$texlive_release
			TEXMFCONFIG $HOME/.texlive$texlive_release/texmf-config
			TEXMFHOME $HOME/texmf
			TEXMFLOCAL $HOME/.opt/texlive/texmf-local
			TEXMFSYSCONFIG $HOME/.opt/texlive/$texlive_release/texmf-config
			TEXMFSYSVAR $HOME/.opt/texlive/$texlive_release/texmf-var
			TEXMFVAR $HOME/.texlive$texlive_release/texmf-var
			binary_x86_64-linux 1
			collection-basic 1
			collection-fontsrecommended 1
			collection-latex 1
			collection-xetex 1
			instopt_adjustpath 0
			instopt_adjustrepo 1
			instopt_letter 0
			instopt_portable 0
			instopt_write18_restricted 1
			tlpdbopt_autobackup 1
			tlpdbopt_backupdir tlpkg/backups
			tlpdbopt_create_formats 1
			tlpdbopt_desktop_integration 1
			tlpdbopt_file_assocs 1
			tlpdbopt_generate_updmap 0
			tlpdbopt_install_docfiles 0
			tlpdbopt_install_srcfiles 0
			tlpdbopt_post_code 1
			tlpdbopt_sys_bin /usr/local/bin
			tlpdbopt_sys_info /usr/local/share/info
			tlpdbopt_sys_man /usr/local/share/man
			tlpdbopt_w32_multi_user 1
		EOF

		perl "$HOME"/install-tl-*/install-tl --profile=profile

		rm -rf "$HOME"/install-tl* profile

		ln -sfn "$HOME/.opt/texlive/$texlive_release" "$HOME/.opt/texlive/current"

		PATH="$PATH:$HOME/.opt/texlive/current/bin/x86_64-linux"

		tlmgr install "${TEXLIVE_PACKAGES[@]}"
	else
		rm -rf "$HOME"/install-tl* profile
		return 1
	fi
}

configure-applications() {
	if [[ -n $clone_flag ]]; then
		git clone https://github.com/noahvanhaute/dotfiles.git
	elif [[ -d $HOME/.ssh ]]; then
		ssh-keyscan github.com >> "$HOME/.ssh/known_hosts"
		git clone git@github.com:noahvanhaute/dotfiles.git
	else
		return 1
	fi
	(cd "$HOME/dotfiles/" && stow --adopt . && sudo stow etc -t /etc/ && git reset --hard)
}

setup-services() {
	sudo systemctl enable --now keyd
	systemctl enable --now --user mpd mpDris2 syncthing
}

setup-autostart() {
	mkdir -p .config/autostart
	cp /usr/share/applications/org.flameshot.Flameshot.desktop "$HOME/.config/autostart/"
	mkdir -p "$HOME/Pictures/Screenshots/"
}

main() {
	exec 3>&1 4>&2
	exec 1>/dev/null 2>/dev/null

	trap cleanup EXIT
	trap errored=true ERR

	echo -en "$HIDE_CURSOR" >&3

	while getopts 'cn:' option; do
		case $option in
			c)
				clone_flag=true ;;
			n)
				host_name="$OPTARG" ;;
			*)
				echo "Usage: $0 [-c] [-n hostname]" >&4
				exit 1 ;;
		esac
	done

	sudo-timeout

	if ! is-wsl; then
		flatpak-no-pw
	fi

	if [[ -n $host_name ]]; then
		start-spinner 'Setting hostname'
		set-hostname
		stop-spinner
	fi

	if is-wsl; then
		start-spinner 'Configuring WSL'
		configure-wsl
		stop-spinner
	fi

	start-spinner 'Making zypper faster'
	configure-zypper
	stop-spinner

	if ! is-wsl; then
		start-spinner 'Opening some ports'
		open-ports
		stop-spinner
	fi

	start-spinner 'Updating the system'
	update-system
	stop-spinner

	start-spinner 'Installing packages, this might take a while'
	if is-wsl; then
		install-wsl-packages
		error-message 'failed to install WSL packages'
	fi
	install-essential-packages
	error-message 'failed to install essential packages'
	if ! is-wsl; then
		install-desktop-packages
		error-message 'failed to install essential packages'
		install-codecs
		error-message 'failed to install codecs'
		install-flatpaks
		error-message 'failed to install flatpaks'
	fi
	install-texlive
	error-message 'failed to install texlive'
	stop-spinner

	start-spinner 'Configuring applications'
	configure-applications
	stop-spinner

	if ! is-wsl; then
		start-spinner 'Setting up services'
		setup-services
		stop-spinner

		start-spinner 'Setting up autostart'
		setup-autostart
		stop-spinner
	fi

	echo 'Setup complete, you should reboot your system' >&3
}

main "$@"
